<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PortableXNB\PortableXNB.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Resources\" />
        <Resource Include="Resources\*" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NAudio.WaveFormRenderer" Version="2.0.0" />
      <PackageReference Include="Spooksoft.HexEditor" Version="1.0.3" />
    </ItemGroup>

</Project>
